# Generated by Django 2.0.1 on 2018-01-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180130_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='supplier_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='supplier_tel',
            field=models.IntegerField(null=True),
        ),
    ]
