# Generated by Django 2.0.1 on 2018-01-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180130_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='application_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='device_ip',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='end_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='ops_tel',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='supplier_tel',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
